/**
 * Writes docs/figma/alpenglow-variables.json from the TypeScript token source:
 * every primitive with its hex (and alpha), every theme token as a pair of
 * aliases, and the Figma scopes each group takes. It is the file the Figma
 * plugin prompt in docs/figma/apply-variables.md reads, so the Figma
 * collections are derived from the same source as the two stylesheets and
 * cannot drift from them by hand.
 *
 * Run: npx tsx scripts/export-figma.ts
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { primitives, alphaPrimitives } from '../src/tokens/primitives.js';
import { theme } from '../src/tokens/theme.js';
import { spacing, radius, borderWidth } from '../src/tokens/scale.js';

/**
 * Figma variable scopes per group. Setting them is the step agents skip; the
 * default puts every token in every picker.
 */
const SCOPES: Record<string, string[]> = {
  'color/surface': ['FRAME_FILL', 'SHAPE_FILL'],
  'color/text': ['TEXT_FILL'],
  'color/interactive': ['FRAME_FILL', 'SHAPE_FILL', 'TEXT_FILL'],
  'color/border': ['STROKE_COLOR'],
  spacing: ['GAP', 'WIDTH_HEIGHT'],
  radius: ['CORNER_RADIUS'],
  'border-width': ['STROKE_FLOAT'],
};

const out = {
  $description:
    'Alpenglow variables for Figma, derived from src/tokens. Three collections: Primitives (hidden, one mode), Theme (Light then Dark, aliases only), Scale (one mode). Generated by scripts/export-figma.ts — do not edit by hand.',
  collections: {
    'Alpenglow Primitives': {
      modes: ['Value'],
      hiddenFromPublishing: true,
      variables: [
        ...Object.entries(primitives).map(([name, hex]) => ({ name, type: 'COLOR', hex })),
        ...Object.entries(alphaPrimitives).map(([name, { hex, alpha }]) => ({ name, type: 'COLOR', hex, alpha })),
      ],
    },
    'Alpenglow Theme': {
      modes: ['Light', 'Dark'],
      hiddenFromPublishing: false,
      variables: Object.entries(theme).map(([name, entry]) => ({
        name: `color/${name}`,
        type: 'COLOR',
        alias: { Light: entry.light, Dark: entry.dark },
        scopes: SCOPES[`color/${name.split('/')[0]}`],
        description: entry.use,
      })),
    },
    'Alpenglow Scale': {
      modes: ['Value'],
      hiddenFromPublishing: false,
      variables: [
        ...Object.entries(spacing).map(([k, v]) => ({ name: `spacing/${k}`, type: 'FLOAT', value: v, scopes: SCOPES.spacing })),
        ...Object.entries(radius).map(([k, v]) => ({ name: `radius/${k}`, type: 'FLOAT', value: v, scopes: SCOPES.radius })),
        ...Object.entries(borderWidth).map(([k, v]) => ({ name: `border-width/${k}`, type: 'FLOAT', value: v, scopes: SCOPES['border-width'] })),
      ],
    },
  },
};

mkdirSync('docs/figma', { recursive: true });
writeFileSync('docs/figma/alpenglow-variables.json', JSON.stringify(out, null, 2) + '\n');
console.log(
  `docs/figma/alpenglow-variables.json: ${out.collections['Alpenglow Primitives'].variables.length} primitives, ${out.collections['Alpenglow Theme'].variables.length} theme tokens, ${out.collections['Alpenglow Scale'].variables.length} scale values`,
);
